### PR TITLE
Groovy++ version of  benchmark

### PR DESCRIPTION
**Pull request by alextkachman**
groovy++ version. runs a bit (12-15%) faster than java. groovy++ v.0.4.297 with groovy 1.8.0

### CODE REVIEW

**Comment by dnene** [comment]
Ok. Thanks. Will review later tonight.

On Wed, Aug 24, 2011 at 12:24 PM, alextkachman
reply@reply.github.com
wrote:

**Comment by alextkachman** [comment]
I've also added OO version of groovy++ benchmark

**Comment by dnene** [comment]
Ok. Thank you. Should be acting on it later today.

On Sun, Aug 28, 2011 at 2:16 PM, alextkachman
reply@reply.github.com
wrote:

> I've also added OO version of groovy++ benchmark
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dnene/josephus/pull/5#issuecomment-1923123

## 

---

http://blog.dhananjaynene.com twitter: @dnene google plus:
http://gplus.to/dhananjaynene

**Comment by alextkachman** [comment]
I feel very sad that you removed benchmark results from the post. What was the point to make it fast if nobody knows :(

**Pull request closed without merging**
